# Generated by Django 3.1.3 on 2020-12-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Produs')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Imagine')),
                ('description', models.TextField(null=True, verbose_name='Caracteristici')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('gender', models.CharField(max_length=20, verbose_name='Gen')),
                ('season', models.CharField(max_length=20, verbose_name='Sezon')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Mărime')),
                ('color', models.CharField(max_length=255, verbose_name='Culoare')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Produs')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Imagine')),
                ('description', models.TextField(null=True, verbose_name='Caracteristici')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('gender', models.CharField(max_length=20, verbose_name='Gen')),
                ('season', models.CharField(max_length=20, verbose_name='Sezon')),
                ('style', models.CharField(max_length=20, verbose_name='Stil')),
                ('size', models.CharField(max_length=3, verbose_name='Mărime')),
                ('color', models.CharField(max_length=255, verbose_name='Culoare')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
