# Generated by Django 3.1.3 on 2020-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.TextField(null=True, verbose_name='Detalii'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(verbose_name='Preț'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(null=True, verbose_name='Detalii'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(verbose_name='Preț'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='description',
            field=models.TextField(null=True, verbose_name='Detalii'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.IntegerField(verbose_name='Preț'),
        ),
    ]
