# Generated by Django 3.1.3 on 2020-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201207_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(max_length=255, verbose_name='Gen'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(max_length=255, verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(max_length=5, verbose_name='Mărime'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='style',
            field=models.CharField(max_length=255, verbose_name='Stil'),
        ),
    ]
