# Generated by Django 3.1.3 on 2020-12-28 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201219_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Preț final'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preț final'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prenumele')),
                ('last_name', models.CharField(max_length=255, verbose_name='Numele')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Adresa')),
                ('status', models.CharField(choices=[('new', 'Comandă nouă'), ('in_progress', 'Comanda în procesare'), ('is_ready', 'Comanda în livrare'), ('completed', 'Comanda executată')], default='new', max_length=100, verbose_name='Statut comandă')),
                ('buying_type', models.CharField(choices=[('self', 'Ridicare personală'), ('delivery', 'Livrare')], default='self', max_length=100, verbose_name='Tip comandă')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentarii')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data comenzii')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data livrării')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Comanda')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='mainapp.customer', verbose_name='Cumpărător')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='mainapp.Order', verbose_name='Comenzile mele'),
        ),
    ]
