# Generated by Django 3.1.3 on 2020-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20201229_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Ridicare personală'), ('delivery', 'Livrare')], default='self', max_length=100, verbose_name='Selectați'),
        ),
    ]
